name: Sync To Gitee

on: [push, delete, create]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                  source-repo: "git@github.com:bianzuilun/bianzuilun.github.io.git"
                  destination-repo: "git@gitee.com:BianZuiLunLunLun/bianzuilun.gitee.io.git"
